### ISSUE TITLE
Staging gEAR-Grammatical change

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#824]
@adkinsrs @JPReceveur 
I talk to 2 persons in the lab and we agreed that the sentence below should be changed to one of the following:
- Neither the given gene symbol(s) nor corresponding orthologs were found in this dataset
- The given gene symbol(s) and corresponding orthologs were not found in this dataset
![image](https://github.com/user-attachments/assets/a1215449-d3dc-4021-ac6d-f03f13b227a2)

**Comment by adkinsrs** [comment]
Fixed

**Comment by beamilon** [comment]
@adkinsrs 
The sentence is still incorrect because it has a double negative. It should be: Neither the given gene symbol(s) nor corresponding orthologs were found in this dataset.
