### ISSUE TITLE
3 New projection errors

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#873]
1] i am getting the "Error: Something went wrong with the projection-creating step." error for all datasets when i try this projection:
https://nemoanalytics.org/p?p=p&l=f1b93141&c=e36cac7a&algo=nmf
i have done many other projections with this dataset collection, so im guessing its the gene list.

2] for dataset "HIV infection and anti-retroviral treatment (ART) in cerebral organoids containing microglia." in this projection link i am getting "Encountered error: Cannot set a DataFrame with multiple columns to the single column y_rounded":
https://nemoanalytics.org/projection.html?algo=pca&c=fc5b3499&l=623b2c0a

3] for all datasets in the following 3 links (same data collection as in item 2 above) using the same data colleciton, i get "Error: Something went wrong with the projection-creating step." for all datasets. the 3 links are 3 different related nmf projections, so guessing its something about the gene lists
https://nemoanalytics.org/projection.html?algo=nmf&c=6dd8e159&l=623b2c0a
https://nemoanalytics.org/projection.html?algo=nmf&c=907b2a3b&l=623b2c0a
https://nemoanalytics.org/projection.html?algo=nmf&c=c96bfdc1&l=623b2c0a

**Comment by adkinsrs** [comment]
For 1) it's a new error to me. `'DataFrame' object has no attribute 'iteritems'`. This is being called within the cloud run function and I am not explicitly calling the "iteritems" function, so I'm guessing it's related to the rpy2 module.  Bit of a conundrum since I needed to keep rpy2 locked into a certain version due to issues in more recent versions.

**Comment by adkinsrs** [comment]
https://github.com/rpy2/rpy2/pull/946

**Comment by adkinsrs** [comment]
There's a couple options I can do.

a) When I had rebuilt the cloud run function, I had updated Pandas from v1.x to v2.x (to keep aligned with gEAR packages), which may have contributed to this issue as well.  I can backport that to v1.x
b) Update to the latest version of rpy2 (v3.5.16) which should resolve this "iteritems" issue, and hopefully my previous issues with rpy2 beyond 3.5.1 (specifically the 3.5.2 - 3.5.4 range) would be resolved.

Both of these would require a rebuild of the cloud run function, but I think b) would require more comprehensive testing than a).  Fortunately we have staging tags for the cloud run function, so I can test locally and use the staging tags

**Comment by adkinsrs** [comment]
Pasting these for my future reference (so I can close the tabs)

https://github.com/rpy2/rpy2/issues/1004
https://github.com/rpy2/rpy2/issues/1057

**Comment by adkinsrs** [comment]
Regarding backporting pandas....

I had rebuilt and ran the cloud run image, and it kept failing (which was hard to diagnose given the "permission denied for cloud logging" errors). Fortunately I was able to filter by a particular InstanceId label and find the issue.  ProjectR was not installed (though the build was successful).

It seems a) I needed to update the projectR install to use the github repo location instead of the bioconductor one which is deprecated.  And b) the Matrix package dependency will not install because the earliest findable version on CRAN without going into the archive requires R v4.4.0+ (I was using R 4.3.1). And since the CRAN archives make it difficult to determine what package version correlates to R version, I am now updating R to 4.4.0

**Comment by adkinsrs** [comment]
@carlocolantuoni I'm letting 1) run right now.  I will close this ticket if it goes through without issues, and I'll let you do 3) in your spare time.

Eventually, I will update the pandas package again as well as rpy2 to see if I can get the more recent versions to work in the cloud run function.  And if they do, then I'll update our "production" function tag to point to those revisions.

**Comment by carlocolantuoni** [comment]
hey shaun,

of the original links posted in the 1st item of this ticket, for the first link i am getting the errors listed below :

1] in this projection link: https://nemoanalytics.org/p?p=p&l=f1b93141&c=e36cac7a&algo=nmf

i am getting the following errors for the following datasets (the last 3 datasets are subsets of the same big one, so if yo can tell me whats oing wrong with the gene annotation there i may be able to fix all 3)

Cell type-specific effects of childhood inflammation during the postnatal maturation of the human cerebellum (Ament et al Science Transl Med 2023) - all cell types downsampled to 50k.
	"Error: Something went wrong with the projection-creating step."
Mouse (6 months), scRNA-seq, immune cells from whole brains of AD model (5xFAD) (Amit)
	"Could not retrieve analysis."
Single-cell analysis of prenatal and postnatal human cortical development - Microglia (Velmeshev et al., Science 2023)
	"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."
Single-cell analysis of prenatal and postnatal human cortical development - Vascular (Velmeshev et al., Science 2023)
	"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."
Single-cell analysis of prenatal and postnatal human cortical development - Pericyte (Velmeshev et al., Science 2023)
	"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."

**Comment by carlocolantuoni** [comment]
none of the links listed in original items 2 and 3 load - did you do away with using "c=" as a short version of "projection_source="?
can we get this back? i have many links setup/sent out using that convention

**Comment by carlocolantuoni** [comment]
all the links in original item 3 work now if i swap c= out and projection_source= in

**Comment by adkinsrs** [comment]
The "c" short-hand form only works when the link starts with https://nemoanalytics.org/p? and has "page=p" added (to go to projection instead of the expression page)

**Comment by adkinsrs** [comment]
Closing the ticket since the issue is resolved again.

For 2) I can't help but notice that you are using projection source ID "fc5b3499" which is a non-public version of ID "384bb3d0" it appears (which has a more formal description name.

**Comment by carlocolantuoni** [comment]
hey shaun,

re-opening as i am still getting a few errors for these links after correcting link syntax:

1] in this projection link: https://nemoanalytics.org/p?p=p&l=f1b93141&c=e36cac7a&algo=nmf

i am getting the following errors for the following datasets (the last 3 datasets are subsets of the same big one, so if yo can tell me whats going wrong with the gene annotation there i may be able to fix all 3)

Cell type-specific effects of childhood inflammation during the postnatal maturation of the human cerebellum (Ament et al Science Transl Med 2023) - all cell types downsampled to 50k.
"Error: Something went wrong with the projection-creating step."
Mouse (6 months), scRNA-seq, immune cells from whole brains of AD model (5xFAD) (Amit)
"Could not retrieve analysis."
Single-cell analysis of prenatal and postnatal human cortical development - Microglia (Velmeshev et al., Science 2023)
"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."
Single-cell analysis of prenatal and postnatal human cortical development - Vascular (Velmeshev et al., Science 2023)
"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."
Single-cell analysis of prenatal and postnatal human cortical development - Pericyte (Velmeshev et al., Science 2023)
"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."


2] for dataset "HIV infection and anti-retroviral treatment (ART) in cerebral organoids containing microglia." in this projection link i am getting "Encountered error: Cannot set a DataFrame with multiple columns to the single column y_rounded":
https://nemoanalytics.org/p?p=p&algo=pca&c=fc5b3499&l=623b2c0a

**Comment by carlocolantuoni** [comment]
dont kno how there are 2 ids for the same projection source, but

https://nemoanalytics.org/p?p=p&algo=pca&c=fc5b3499&l=623b2c0a
and
https://nemoanalytics.org/p?p=p&algo=pca&c=384bb3d0&l=623b2c0a

produce the same error

**Comment by adkinsrs** [comment]
Looking into that.  Let's keep this closed and open a new ticket for that error (and I believe there may already be one)

**Comment by carlocolantuoni** [comment]
i think all the other issues in this ticket were solved or pt into other tickets, but these errors remain:

in this projection link: https://nemoanalytics.org/p?p=p&l=f1b93141&c=e36cac7a&algo=nmf

i am getting the following errors for the following datasets (the last 3 datasets are subsets of the same big one, so if yo can tell me whats going wrong with the gene annotation there i may be able to fix all 3)

Cell type-specific effects of childhood inflammation during the postnatal maturation of the human cerebellum (Ament et al Science Transl Med 2023) - all cell types downsampled to 50k.
"Error: Something went wrong with the projection-creating step."

Mouse (6 months), scRNA-seq, immune cells from whole brains of AD model (5xFAD) (Amit)
"Could not retrieve analysis."

Single-cell analysis of prenatal and postnatal human cortical development - Microglia (Velmeshev et al., Science 2023)
"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."

Single-cell analysis of prenatal and postnatal human cortical development - Vascular (Velmeshev et al., Science 2023)
"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."

Single-cell analysis of prenatal and postnatal human cortical development - Pericyte (Velmeshev et al., Science 2023)
"Error: No common genes between the target dataset (20116 genes) and the pattern file (17105 genes)."

**Comment by adkinsrs** [comment]
For the "Could not retrieve analysis" one it is a user_saved analysis where the NeMO Curator account saved the analysis and it was used in the saved curation. Because it is "user_saved" and not "public" it is saved in the user's designated area, but when loading the display it expects to find it in the account space for the currently logged in user (as user_saved displays are meant to be private to that user).

I would suggest either redoing that analysis and setting it to public, which moves it to the "public" designated area, or creating a curation that uses no analysis (or Primary one)

**Comment by adkinsrs** [comment]
For the dataset with the three "Error: No common genes" error, the dataset adata.var.index (where Ensembl ID should go) has gene symbols

**Comment by carlocolantuoni** [comment]
ok thanks for tracking these down - they are a mess - lets leave them for now. thnx
